WebApplication1/Models/Instructor.cs
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class Instructor
{
    public int InstructorId { get; set; }

    public string? InstructorName { get; set; }

    public string? ExpertiseAreas { get; set; }

    public string? Qualifications { get; set; }
    public string UserId { get; set; } // Ensure this property exists
    public virtual ICollection<Assessment> Assessments { get; set; } = new List<Assessment>();


    public virtual UserAcccount UserAccount { get; set; } // Navigation property to UserAccount
    public virtual ICollection<EmotionalFeedback> EmotionalFeedbacks { get; set; } = new List<EmotionalFeedback>();

    public virtual ICollection<InstructorEmail> Emails { get; set; } = new List<InstructorEmail>();

    public virtual ICollection<LearningPath> LearningPaths { get; set; } = new List<LearningPath>();

    public virtual ICollection<Course> Courses { get; set; } = new List<Course>();
}

WebApplication1/Controllers/InstructorController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication1.Models;

public class InstructorController : Controller
{
    private readonly UserManager<UserAcccount> _userManager;
    private readonly MilestoneContext _context;

    public InstructorController(UserManager<UserAcccount> userManager, MilestoneContext context)
    {
        _userManager = userManager;
        _context = context;
    }

    public async Task<IActionResult> InstructorDashboard()
    {
        var user = await _userManager.GetUserAsync(User);
        if (user == null)
        {
            return NotFound("User not found");
        }

        var instructor = await _context.Instructors
            .Include(i => i.Emails)
            .FirstOrDefaultAsync(i => i.UserId == user.Id);

        if (instructor == null)
        {
            return NotFound("Instructor not found");
        }

        var model = new InstructorProfileViewModel
        {
            InstructorId = instructor.InstructorId,
            Name = instructor.InstructorName,
            ExpertiseAreas = instructor.ExpertiseAreas,
            Qualifications = instructor.Qualifications,
            Emails = instructor.Emails.Select(e => e.Email).ToList()
        };

        return View(model);
    }

    [HttpGet]
    public async Task<IActionResult> UpdateProfile()
    {
        var user = await _userManager.GetUserAsync(User);
        if (user == null)
        {
            return NotFound("User not found");
        }

        var instructor = await _context.Instructors
            .Include(i => i.Emails)
            .FirstOrDefaultAsync(i => i.UserId == user.Id);

        if (instructor == null)
        {
            return NotFound("Instructor not found");
        }

        var model = new InstructorProfileViewModel
        {
            InstructorId = instructor.InstructorId,
            Name = instructor.InstructorName,
            ExpertiseAreas = instructor.ExpertiseAreas,
            Qualifications = instructor.Qualifications,
            Emails = instructor.Emails.Select(e => e.Email).ToList()
        };

        return View(model);
    }

    [HttpPost]
    public async Task<IActionResult> UpdateProfile(InstructorProfileViewModel model)
    {
        if (ModelState.IsValid)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return NotFound("User not found");
            }

            var instructor = await _context.Instructors
                .Include(i => i.Emails)
                .FirstOrDefaultAsync(i => i.UserId == user.Id);

            if (instructor == null)
            {
                return NotFound("Instructor not found");
            }

            instructor.InstructorName = model.Name;
            instructor.ExpertiseAreas = model.ExpertiseAreas;
            instructor.Qualifications = model.Qualifications;

            // Update emails
            instructor.Emails.Clear();
            foreach (var email in model.Emails)
            {
                instructor.Emails.Add(new InstructorEmail { Email = email });
            }

            _context.Update(instructor);
            await _context.SaveChangesAsync();

            return RedirectToAction("InstructorDashboard");
        }

        return View(model);
    }

    [HttpGet]
    public IActionResult CreateLearningPath()
    {
        return View();
    }

    [HttpPost]

    public async Task<IActionResult> CreateLearningPath(LearningPathViewModel model)
    {
        var user = await _userManager.GetUserAsync(User);
        if (user == null)
        {
            return NotFound("User not found");
        }

        var instructor = await _context.Instructors.FirstOrDefaultAsync(i => i.UserId == user.Id);
        if (instructor == null)
        {
            return NotFound("Instructor not found");
        }

        if (ModelState.IsValid)
        {

            var learningPath = new LearningPath
            {
                Rules = model.Rules,
                LearnerStatus = model.LearnerStatus,
                PathDescription = model.PathDescription,
                InstructorId = instructor.InstructorId,
                LearnerId = model.LearnerId
            };


            _context.LearningPaths.Add(learningPath);
            await _context.SaveChangesAsync();

            return RedirectToAction("InstructorDashboard");
        }

        return View(model);
    }

    [HttpGet]
    public IActionResult CreateForum()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> CreateForum(DiscussionForum model)
    {
        if (ModelState.IsValid)
        {
            _context.DiscussionForums.Add(model);
            await _context.SaveChangesAsync();
            return RedirectToAction("InstructorDashboard");
        }
        return View(model);
    }

    [HttpGet]
    public async Task<IActionResult> AddPost(int forumId)
    {
        var forum = await _context.DiscussionForums.FindAsync(forumId);
        if (forum == null)
        {
            return NotFound("Forum not found");
        }
        var model = new Post { ForumId = forumId };
        return View(model);
    }

    [HttpPost]
    public async Task<IActionResult> AddPost(Post model)
    {
        if (ModelState.IsValid)
        {
            model.CreatedAt = DateTime.Now;
            _context.Posts.Add(model);
            await _context.SaveChangesAsync();
            return RedirectToAction("ViewForum", new { id = model.ForumId });
        }
        return View(model);
    }

    public async Task<IActionResult> ViewForum(int id)
    {
        var forum = await _context.DiscussionForums
            .Include(f => f.Posts)
            .FirstOrDefaultAsync(f => f.ForumId == id);

        if (forum == null)
        {
            return NotFound("Forum not found");
        }
        return View(forum);
    }


    public async Task<IActionResult> ViewLearningPaths()
    {
        var user = await _userManager.GetUserAsync(User);
        if (user == null)
        {
            return NotFound("User not found");
        }

        var instructor = await _context.Instructors
            .FirstOrDefaultAsync(i => i.UserId == user.Id);

        if (instructor == null)
        {
            return NotFound("Instructor not found");
        }

        var learningPaths = await _context.LearningPaths
            .Where(lp => lp.InstructorId == instructor.InstructorId)
            .ToListAsync();

        return View(learningPaths);
    }
}

WebApplication1/Controllers/InstructorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class InstructorsController : Controller
    {
        private readonly MilestoneContext _context;

        public InstructorsController(MilestoneContext context)
        {
            _context = context;
        }

        // GET: Instructors
        public async Task<IActionResult> Index()
        {
            return View(await _context.Instructors.ToListAsync());
        }

        // GET: Instructors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var instructor = await _context.Instructors
                .FirstOrDefaultAsync(m => m.InstructorId == id);
            if (instructor == null)
            {
                return NotFound();
            }

            return View(instructor);
        }

        // GET: Instructors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Instructors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("InstructorId,InstructorName,ExpertiseAreas,Qualifications")] Instructor instructor)
        {
            if (ModelState.IsValid)
            {
                _context.Add(instructor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(instructor);
        }

        // GET: Instructors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var instructor = await _context.Instructors.FindAsync(id);
            if (instructor == null)
            {
                return NotFound();
            }
            return View(instructor);
        }

        // POST: Instructors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("InstructorId,InstructorName,ExpertiseAreas,Qualifications")] Instructor instructor)
        {
            if (id != instructor.InstructorId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(instructor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InstructorExists(instructor.InstructorId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(instructor);
        }

        // GET: Instructors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var instructor = await _context.Instructors
                .FirstOrDefaultAsync(m => m.InstructorId == id);
            if (instructor == null)
            {
                return NotFound();
            }

            return View(instructor);
        }

        // POST: Instructors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var instructor = await _context.Instructors.FindAsync(id);
            if (instructor != null)
            {
                _context.Instructors.Remove(instructor);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool InstructorExists(int id)
        {
            return _context.Instructors.Any(e => e.InstructorId == id);
        }


    }

}

WebApplication1/Views/Instructor/AddPost.cshtml
@model WebApplication1.Models.Post

<h2>Add Post to Forum</h2>

<form asp-action="AddPost" method="post">
    <div class="form-group">
        <label asp-for="Content" class="control-label"></label>
        <textarea asp-for="Content" class="form-control"></textarea>
        <span asp-validation-for="Content" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="hidden" asp-for="ForumId" />
        <input type="submit" value="Add Post" class="btn btn-primary" />
    </div>
</form>

WebApplication1/Views/Instructor/CreateForum.cshtml
@model WebApplication1.Models.DiscussionForum

<h2>Create Discussion Forum</h2>

<form asp-action="CreateForum" method="post">
    <div class="form-group">
        <label asp-for="Title" class="control-label"></label>
        <input asp-for="Title" class="form-control" />
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description" class="control-label"></label>
        <textarea asp-for="Description" class="form-control"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary" />
    </div>
</form>

WebApplication1/Views/Instructor/CreateLearningPath.cshtml
@model WebApplication1.Models.LearningPathViewModel

<h2>Add New Learning Path</h2>

<form asp-action="CreateLearningPath" method="post">
    <div class="form-group">
        <label asp-for="Rules" class="control-label"></label>
        <input asp-for="Rules" class="form-control" />
        <span asp-validation-for="Rules" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="LearnerStatus" class="control-label"></label>
        <input asp-for="LearnerStatus" class="form-control" />
        <span asp-validation-for="LearnerStatus" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="PathDescription" class="control-label"></label>
        <input asp-for="PathDescription" class="form-control" />
        <span asp-validation-for="PathDescription" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="LearnerId" class="control-label"></label>
        <input asp-for="LearnerId" class="form-control" />
        <span asp-validation-for="LearnerId" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary" />
    </div>
</form>

WebApplication1/Views/Instructor/InstructorDashboard.cshtml
@model InstructorProfileViewModel

<h2>Instructor Dashboard</h2>

<p>Welcome, @Model.Name!</p>

<p>Emails:</p>
<ul>
    @foreach (var email in Model.Emails)
    {
        <li>@email</li>
    }
</ul>

<p>Expertise Areas: @Model.ExpertiseAreas</p>
<p>Qualifications: @Model.Qualifications</p>

<a asp-controller="Instructor" asp-action="UpdateProfile" class="btn btn-primary">Update Profile</a>
<a asp-controller="Instructor" asp-action="ViewLearningPaths" class="btn btn-info">View Learning Paths</a>
<a asp-controller="Instructor" asp-action="CreateLearningPath" class="btn btn-success">Add New Learning Path</a>

<hr />

<h3>Manage Discussion Forums</h3>
<a asp-controller="Instructor" asp-action="CreateForum" class="btn btn-primary">Create New Forum</a>
<a asp-controller="Instructor" asp-action="ViewForum" class="btn btn-secondary">View Forums</a>

WebApplication1/Views/Instructor/UpdateProfile.cshtml
@model InstructorProfileViewModel

<h2>Update Profile</h2>

<form asp-action="UpdateProfile" method="post">
    <div class="form-group">
        <label for="Name">Full Name</label>
        <input type="text" class="form-control" id="Name" name="Name" value="@Model.Name" />
    </div>
    <div class="form-group">
        <label for="Email">Emails</label>
        @for (int i = 0; i < Model.Emails.Count; i++)
        {
            <input type="email" class="form-control" id="Emails" name="Emails[@i]" value="@Model.Emails[i]" />
        }
    </div>
    <div class="form-group">
        <label for="ExpertiseAreas">Expertise Areas</label>
        <input type="text" class="form-control" id="ExpertiseAreas" name="ExpertiseAreas" value="@Model.ExpertiseAreas" />
    </div>
    <div class="form-group">
        <label for="Qualifications">Qualifications</label>
        <input type="text" class="form-control" id="Qualifications" name="Qualifications" value="@Model.Qualifications" />
    </div>
    <button type="submit" class="btn btn-primary">Save Changes</button>
</form>

WebApplication1/Views/Instructor/ViewForum.cshtml
@model WebApplication1.Models.DiscussionForum

<h2>@Model.Title</h2>
<p>@Model.Description</p>

<h3>Posts</h3>
@if (Model.Posts != null && Model.Posts.Any())
{
    <ul>
        @foreach (var post in Model.Posts)
        {
            <li>
                <strong>@post.CreatedAt?.ToString("yyyy-MM-dd")</strong>: @post.Content
            </li>
        }
    </ul>
}
else
{
    <p>No posts yet.</p>
}

<a asp-controller="Instructor" asp-action="AddPost" asp-route-forumId="@Model.ForumId" class="btn btn-primary">Add Post</a>

WebApplication1/Views/Instructor/ViewLearningPaths.cshtml
@model IEnumerable<WebApplication1.Models.LearningPath>

<table class="table">
    <thead>
        <tr>
            <th>Path ID</th>
            <th>Rules</th>
            <th>Learner Status</th>
            <th>Path Description</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var path in Model)
        {
            <tr>
                <td>@path.PathId</td>
                <td>@path.Rules</td>
                <td>@path.LearnerStatus</td>
                <td>@path.PathDescription</td>
            </tr>
        }
    </tbody>
</table>